<?php if(sfConfig::get('app_gn_site_is_private', false)): ?>

_site_page:
  enabled:     true

<?php else: ?>

index:
  enabled:     true
show:
  enabled:     true
_navigation:
  enabled:     true
  contextual:  true

<?php endif; ?>
