<?php if(sfConfig::get('app_rt_site_is_private', false)): ?>



<?php else: ?>

index:
  enabled:     true
show:
  enabled:     false
_navigation:
  enabled:     true
  contextual:  true

_site_page:
  enabled:     true

<?php endif; ?>
