rtSitePage:
  actAs:
    rtSearchTemplate:
      fields:      [menu_title, title, content, description]
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    menu_title:      string(255)
#    menu_position:   { type: integer, default: 1 }
    display_in_menu: { type: boolean, default: 1 }
  inheritance:
    type:            concrete
    extends:         rtPage
